[build]
  command = "cd src/nextjs && yarn install && yarn build && npx next export"
  publish = "src/nextjs/out"

[template.environment]
  LIFF_ID = "Your LIFF ID which is aquired from LINE Dev Center"
